"""second migrations

Revision ID: 8685908de4e9
Revises: 94f83e67fe8e
Create Date: 2023-02-22 03:10:41.647751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8685908de4e9'
down_revision = '94f83e67fe8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
